class_name: ConnectomeODEImageClassifier
rnn_kwargs:
  connectivity_hh: connectivity/sunny/connectivity_hh.pt
  connectivity_ih: connectivity/sunny/connectivity_ih.pt
  input_indices: connectivity/sunny/input_indices.pt
  hidden_init_mode: zeros
  nonlinearity: Tanh
  use_layernorm: false
  bias: true
num_classes: 10
fc_dim: 256
dropout: 0.5

# @package _global_
train:
  forward_kwargs:
    num_steps: 1
