# @package _global_
model:
  class_name: ConnectomeODEClassifier
  rnn_kwargs:
    input_size: 784
    num_neurons: 47521
    output_size: 1000
    connectome: connectivity/sunny/connectome.pt
    input_projection: connectivity/sunny/input_projection_matrix.pt
    output_projection: connectivity/sunny/output_projection_matrix.pt
    batch_first: false
    compile_solver_kwargs:
      mode: max-autotune
      dynamic: false
      fullgraph: true
    compile_update_fn_kwargs:
      mode: max-autotune
      dynamic: false
      fullgraph: true
  fc_dim: 256
  dropout: 0.5
train:
  forward_kwargs:
    num_evals: 2
