# @package _global_
model:
  class_name: ConnectomeODEClassifier
  rnn_kwargs:
    input_size: 4751
    hidden_size: 47521
    connectivity_hh: connectivity/sunny/connectivity_hh.pt
    connectivity_ih: connectivity/sunny/connectivity_ih.pt
    num_neuron_types: 2
    neuron_type_class:
      - excitatory
      - inhibitory
    neuron_type_indices:
      - connectivity/sunny/indices_neuron_type_1.pt
      - connectivity/sunny/indices_neuron_type_2.pt
    neuron_type_nonlinearity: Sigmoid
    neuron_type_tau_init:
      - 1.5
      - 1
    train_tau: false
    compile_solver_kwargs:
      mode: max-autotune
      dynamic: false
      fullgraph: true
  fc_dim: 256
  dropout: 0.5
train:
  forward_kwargs:
    num_steps: 2
