class_name: ConnectomeODEImageClassifier
rnn_kwargs:
  sheet_size: [150, 300]
  synapse_std: 10
  synapses_per_neuron: 32
  input_indices: connectivity/V1_indices_flat.pt
  output_indices: connectivity/V4_indices_flat.pt
  nonlinearity: Tanh
  use_layernorm: false
  bias: true
num_classes: 10
fc_dim: 256
dropout: 0.5

# @package _global_
train:
  num_steps: 1
