rnn_kwargs:
  in_size: null # Must be provided (height, width)
  in_channels: null # Must be provided (height, width)
  h_pyr_channels: 32
  h_inter_channels: null
  fb_channels: null
  exc_kernel_size: [3, 3]
  inh_kernel_size: null
  fb_kernel_size: null
  use_three_compartments: false
  immediate_inhibition: false
  num_layers: 1
  inter_mode: same
  layer_time_delay: false
  exc_rectify: true
  inh_rectify: true
  hidden_init_mode: zeros
  fb_init_mode: zeros
  out_init_mode: zeros
  fb_adjacency: null
  pool_kernel_size: null
  pool_stride: null
  pool_global: true
  bias: true
  pre_inh_activation: gelu
  post_inh_activation: gelu
  post_integration_activation: null
  tau_mode: channel
  batch_first: true
arch: crnn
num_classes: 10
fc_dim: 256
dropout: 0.5
