defaults:
  - crnn
  - _self_

rnn_kwargs:
  h_pyr_channels: [16, 32, 64, 128]
  h_inter_channels:
    - [8, 8]
    - [16, 16]
    - [32, 32]
    - [64, 64]
  fb_channels: [16, 32, 64, 128]
  fb_adjacency:
    - [0, 0, 0, 0]
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
  use_three_compartments: false
  immediate_inhibition: false
flush_hidden: true
flush_out: true
flush_fb: true
num_classes: 6
fc_dim: 256
dropout: 0.5
