defaults:
  - crnn
  - _self_

rnn_kwargs:
  h_pyr_channels: [16, 32, 64, 128]
  h_inter_channels:
    - [16]
    - [32]
    - [64]
    - [128]
  fb_channels: null
  fb_adjacency: null
  use_three_compartments: false
  immediate_inhibition: false
