class_name: CRNNImageClassifier # e.g. CRNNImageClassifier, TopographicalImageClassifier

rnn_kwargs:
  # Layer configuration parameters
  num_layers: 1
  layer_time_delay: false
  batch_first: true

  # Layer-specific configuration
  layer_kwargs: null # Must provide a list of layer kwargs

  # Common parameters for all layers
  common_layer_kwargs:
    spatial_size: [32, 32] # Spatial size of the input image
    in_channels: 3 # Number of input channels
    out_channels: 32 # Number of output channels for the layer
    num_neuron_types: 1 # Number of neuron types (e.g., excitatory, inhibitory)
    neuron_channels: 16 # Number of channels per neuron type
    neuron_type: "excitatory" # Type of neuron ("excitatory" or "inhibitory")
    neuron_spatial_mode: "same" # Spatial mode for neuron ("same" or "valid")
    fb_channels: null # Number of feedback channels
    conv_connectivity: [[1, 0], [0, 1]] # Connectivity matrix for convolutions
    conv_rectify: false # Whether to rectify convolution outputs
    conv_kernel_size: [3, 3] # Kernel size for convolutions
    conv_activation: null # Activation function for convolutions
    conv_bias: true # Whether to use bias in convolutions
    post_agg_activation: "tanh" # Activation function after aggregation
    tau_mode: "channel" # Mode for tau parameter ("channel" or "pixel")
    tau_init_mode: "zeros" # Initialization mode for tau
    default_hidden_init_mode: "zeros" # Initialization mode for hidden states
    default_fb_init_mode: "zeros" # Initialization mode for feedback
    default_out_init_mode: "zeros" # Initialization mode for output

  # Feedback parameters
  fb_connectivity: null # Connectivity matrix for feedback
  fb_activations: null # Activation functions for feedback
  fb_rectify: false # Whether to rectify feedback
  fb_kernel_sizes: null # Kernel sizes for feedback

# Classifier parameters
num_classes: 10 # Number of output classes
fc_dim: 512 # Dimension of fully connected layer
dropout: 0.2 # Dropout rate

# Training parameters
matmul_precision: "highest" # Precision for matrix multiplication
