defaults:
  - topographical_rnn
  - _self_

rnn_kwargs:
  sheet_size: null
  synapse_std: null
  synapses_per_neuron: null
  self_recurrence: null
  connectivity_hh: connectivity/
  connectivity_ih: null
  num_classes: 10
  batch_first: true
  input_indices: null
  output_indices: connectivity/V4_indices_flat.pt
  rnn_nonlinearity: relu
  out_nonlinearity: relu
  use_layernorm: true
  bias: true
