defaults:
  - topographical_rnn
  - _self_

rnn_kwargs:
  sheet_size: [150, 300]
  synapse_std: 10
  synapses_per_neuron: 32
  self_recurrence: true
  connectivity_hh: null
  connectivity_ih: null
  num_classes: 10
  batch_first: true
  input_indices: connectivity/V1_indices_flat.pt
  output_indices: connectivity/V4_indices_flat.pt
  nonlinearity: tanh
  use_layernorm: true
  bias: true
arch: topographical_rnn
num_classes: 10
fc_dim: 256
dropout: 0.5
