# 1 hybrid area with 1 hybrid neuron type
class_name: SpatiallyEmbeddedClassifier
rnn_kwargs:
  num_areas: 2
  area_kwargs:
    - in_size: [128, 128]
      in_channels: 1
      out_channels: 32
      num_neuron_subtypes: 32
      neuron_type_nonlinearity: "Tanh"
      inter_neuron_type_spatial_extents: [5, 5]
    - in_size: [32, 32]
      in_channels: 32
      out_channels: 64
      num_neuron_subtypes: 64
      neuron_type_nonlinearity: "Tanh"
      inter_neuron_type_spatial_extents: [3, 3]
