# 1 hybrid area with 1 hybrid neuron type
class_name: SpatiallyEmbeddedClassifier
rnn_kwargs:
  num_areas: 1
  area_kwargs:
    - in_size: [48, 48]
      in_channels: 4
      out_channels: 32
      num_neuron_subtypes: 16
      neuron_type_nonlinearity: Sigmoid
      inter_neuron_type_spatial_extents: [3, 3]