site_name: bioplnn-zoo
site_url: https://sitename.example

nav:
  - Home: index.md
  - Tutorials and Examples: tutorials/index.md
  - API Reference: reference/index.md
  - FAQ: faq.md
  - Contributing:
    - How to contribute: contribute.md
    - Code of Conduct: code_of_conduct.md
  - Citation: citation.md
  - Credits: credits.md

theme:
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  palette:
      # Dark Mode
      - scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Dark mode
        primary: lime
        accent: light green

      # Light Mode
      - scheme: default
        toggle:
          icon: material/weather-night
          name: Light mode
        primary: indigo
        accent: deep orange

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            heading_level: 2
            show_root_toc_entry: true
            show_symbol_type_toc: true
            show_root_full_path: false
            show_root_heading: true