sheet_size: [150, 300]
connectivity_std: 10
synapses_per_neuron: 32
num_timesteps: 100
bias: True
num_classes: 10
mm_function: torch_sparse
sparse_format: torch_sparse
batch_first: True
adjacency_matrix_path: Null
self_recurrence: True
input_indices: connection/V1_indices_flat.pt
output_indices: connection/V4_indices_flat.pt
activation: relu