input_size: [32, 32]
input_dim: 3
h_pyr_dim: [16, 32, 64, 64]
h_inter_dims: null
fb_dim: null
exc_kernel_size: 
- [3, 3]
- [3, 3]
- [3, 3]
- [3, 3]
inh_kernel_size: 
- [3, 3]
- [3, 3]
- [3, 3]
- [3, 3]
num_compartments: 1
immediate_inhibition: true
num_layers: 4
inter_mode: half
layer_time_delay: false
exc_rectify: false
hidden_init_mode: zeros
fb_init_mode: zeros
out_init_mode: zeros
fb_adjacency: null
pool_kernel_size: [5, 5]
pool_stride: [2, 2]
bias: true
pre_inh_activation: tanh
post_inh_activation: null