activations:
  num_samples: 10
  save_activations: true
  save_root: activations/ei
  shuffle_test: true
checkpoint:
  epoch: null
  load: false
  root: checkpoints/ei
  run: avid-disco-3472
compile:
  disable: true
criterion:
  class_name: CrossEntropyLoss
data:
  batch_size: 256
  dataset: mnist
  num_workers: 8
  root: data
  shuffle_test: true
debug_level: 1
debug_num_batches: null
deterministic: false
layer_one_in_channels_override: 1
matmul_precision: high
model:
  class_name: SpatiallyEmbeddedClassifier
  num_classes: 10
  rnn_kwargs:
    batch_first: false
    layer_kwargs:
    - in_channels: 1
      out_channels: 32
      spatial_size:
      - 32
      - 32
optimizer:
  betas:
  - 0.9
  - 0.999
  class_name: AdamW
  lr: 0.005
seed: null
tqdm: true
train:
  epochs: 100
  forward_kwargs:
    loss_all_timesteps: false
    num_steps: 5
  grad_clip:
    enable: false
    type: norm
    value: 1.0
  log_freq: 5
wandb:
  group: null
  mode: disabled
  project: bioplnn
