activations:
  num_samples: 10
  save_activations: true
  save_root: activations/ei
  shuffle_test: true
checkpoint:
  epoch: null
  load: false
  root: checkpoints/ei
  run: avid-disco-3472
compile:
  disable: true
criterion:
  class_name: CrossEntropyLoss
data:
  batch_size: 8
  dataset: mnist
  num_workers: 8
  root: data
  shuffle_test: true
debug_level: 1
debug_num_batches: null
deterministic: false
matmul_precision: high
model:
  class_name: ConnectomeODEClassifier
  dropout: 0.5
  fc_dim: 256
  num_classes: 10
  rnn_kwargs:
    batch_first: false
    compile_solver_kwargs:
      dynamic: false
      fullgraph: true
      mode: max-autotune
    connectivity_hh: connectivity/sunny/connectivity_hh.pt
    connectivity_ih: connectivity/sunny/connectivity_ih_mnist.pt
    hidden_size: 47521
    input_size: 784
    nonlinearity: Sigmoid
    output_neurons: connectivity/sunny/output_indices_mnist.pt
optimizer:
  betas:
  - 0.9
  - 0.999
  class_name: AdamW
  lr: 0.005
seed: null
tqdm: true
train:
  epochs: 100
  forward_kwargs:
    loss_all_timesteps: false
    num_steps: 2
  grad_clip:
    enable: false
    type: norm
    value: 1.0
  log_freq: 5
wandb:
  group: null
  mode: disabled
  project: bioplnn
