activations:
  num_samples: 10
  save_activations: true
  save_root: activations/ei
  shuffle_test: true
checkpoint:
  epoch: null
  load: false
  root: checkpoints/ei
  run: avid-disco-3472
compile:
  backend: inductor
  disable: true
  dynamic: null
  fullgraph: true
  mode: reduce-overhead
criterion:
  class_name: CrossEntropyLoss
data:
  batch_size: 256
  dataset: mnist
  num_workers: 0
  root: data
  shuffle_test: true
debug_level: 1
debug_num_batches: null
deterministic: false
layer_one_in_channels_override: 1
matmul_precision: high
model:
  class_name: CRNNImageClassifier
  num_classes: 10
  rnn_kwargs:
    batch_first: false
    layer_kwargs:
    - in_channels: 1
      out_channels: 32
      spatial_size:
      - 32
      - 32
optimizer:
  betas:
  - 0.9
  - 0.999
  class_name: AdamW
  lr: 0.0005
seed: null
tqdm: true
train:
  epochs: 100
  grad_clip:
    enable: false
    type: norm
    value: 1.0
  log_freq: 5
  loss_all_timesteps: true
  num_steps: 5
wandb:
  group: null
  mode: disabled
  project: bioplnn
