defaults:
  - model: null
  - _self_

data:
  dataset: cifar10
  root: data
  retina_path: connectivity/V1_indices.pt
  batch_size: 128
  num_workers: 8
optimizer: 
  fn: adamw
  lr: 0.001
  momentum: 0.9
  beta1: 0.9
  beta2: 0.999
scheduler:
  fn: one_cycle
  pct_start: 0.3
criterion: 
  fn: ce
  loss_all_timesteps: false
visualize:
  enable: false
  save_dir: visualizations
  fps: 4
  frames: [0, 20]
train:
  num_steps: 20
  epochs: 100
  log_freq: 10
  model_dir: models
  grad_clip:
    enable: false
    type: norm
    value: 1.0
checkpoint:
  root: checkpoints/topography
  load: false
  run: test2
  epoch: null
wandb:
  project: Cortical RNN
  mode: online
  group: null
tqdm: true
deterministic: false
seed: 0
foreach: true
matmul_precision: high
debug_level: 2