# experiment/dimensions: choice(channels_64, channels_128)
optimizer.lr: choice(0.0005, 0.0001, 0.00005)
experiment/activation: choice(gelu_gelu, gelu_gelutanh, gelutanh_gelu, gelu_tanh)
# model: choice(e1l, ei1l)

# hydra.launcher.slurm.gres: gpu:1
# data.batch_size: 64

# python examples/ei_trainer.py -m hydra/launcher=slurm +hydra/sweeper/params=mazes \
# wandb.mode=online wandb.group=mazes data=mazes hydra.launcher.slurm.gres=gpu:1 data.batch_size=64