# model.rnn_kwargs.exc_rectify: choice(false, true)
# model.rnn_kwargs.inh_rectify: choice(true, false)
# model.rnn_kwargs.post_inh_activation: choice(null,tanh)
# model.rnn_kwargs.pre_inh_activation: choice(tanh,relu,null)
model.rnn_kwargs.immediate_inhibition: choice(false, true)
model.rnn_kwargs.use_three_compartments: choice(false, true)
model.rnn_kwargs.fb_channels: choice(null, [16, 32, 64, 128])
model.rnn_kwargs.fb_adjacency: choice(null,[[0,0,0,0],[1,0,0,0],[0,1,0,0],[0,0,1,0]],[[0,0,0,0],[1,0,0,0],[1,1,0,0],[1,1,1,0]])
model.rnn_kwargs.h_inter_channels: choice(null,[[16],[32],[64],[128]],[[8,8],[16,16],[32,32],[64,64]],[[4,4,4,4],[8,8,8,8],[16,16,16,16],[32,32,32,32]])

# python src/bioplnn/examples/ei_trainer.py -m hydra/launcher=slurm +hydra/sweeper/params=image_classification wandb.mode=online wandb.group=sweep1 data=mnist model=eifb