defaults:
  - rnn_kwargs: default
  - _self_

rnn_kwargs:
  h_pyr_channels: [16, 32, 64, 128]
  h_inter_channels: 
  - [16]
  - [32]
  - [64]
  - [128]
  fb_channels: [16, 32, 64, 128]
  fb_adjacency: 
  - [0, 0, 0, 0]
  - [1, 0, 0, 0]
  - [1, 1, 0, 0]
  - [1, 1, 1, 0]
  use_three_compartments: false
  immediate_inhibition: false
