defaults:
  - rnn_kwargs: default
  - _self_

rnn_kwargs:
  input_size: [32, 32]
  in_channels: 3
  exc_kernel_size: 
  - [3, 3]
  - [3, 3]
  - [3, 3]
  - [3, 3]
  inh_kernel_size: 
  - [3, 3]
  - [3, 3]
  - [3, 3]
  - [3, 3]
num_classes: 100
fc_channels: 512
dropout: 0.2